/**
 * My Portfolio
 * My portfolio website\'s backend
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateExperienceCommand { 
    companyName?: string | null;
    description?: string | null;
    position?: string | null;
    workType?: string | null;
    city?: string | null;
    fromDate?: string;
    toDate?: string;
    skills?: Array<string> | null;
}

