/**
 * My Portfolio
 * My portfolio website\'s backend
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateEducationCommand { 
    id: number;
    name?: string | null;
    description?: string | null;
    city?: string | null;
    fromDate?: string | null;
    toDate?: string | null;
    educationWebSiteUrl?: string | null;
}

