/**
 * My Portfolio
 * My portfolio website\'s backend
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateLanguageCommand { 
    languageId: number;
    languageLevel?: string | null;
}

